#nullable enable
using System;
using System.Collections.Generic;
using UnityEngine;

namespace CrowdDefense.UI
{
    public static class L
    {
        private static string _locale = "en";

        public static event Action? OnLocaleChanged;

        public static string CurrentLocale => _locale;

        private static readonly Dictionary<string, Dictionary<string, Dictionary<string, string>>> _fallback = new()
        {
            ["UI"] = new()
            {
                ["en"] = new()
                {
                    // ── Tower toolbar ──────────────────────────────────────────────
                    ["toolbar.not_enough_gold"] = "Not enough gold",

                    // ── Speed control ──────────────────────────────────────────────
                    ["hud.speed_label"] = "SPEED",

                    // ── Perk picker ────────────────────────────────────────────────
                    ["perk.pick_title"] = "Choose a perk",
                    ["perk.pick_subtitle"] = "Pick 1 of 3 to continue",
                    ["perk.rarity_common"] = "Common",
                    ["perk.rarity_rare"] = "Rare",
                    ["perk.rarity_epic"] = "Epic",
                    ["perk.rarity_legendary"] = "Legendary",
                    ["perk.placeholder_name"] = "Unknown Perk",
                    ["perk.placeholder_desc"] = "No description available.",

                    // ── HUD pills ───────────────────────────────────────────────────
                    ["hud.gold_label"] = "GOLD",
                    ["hud.wave_label"] = "WAVE",
                    ["hud.hp_label"] = "HP",
                    ["hud.wave_launch"] = "Launch wave [N]",
                    ["hud.wave_launch_bonus"] = "Launch (+30c) [N]",
                    ["hud.wave_progress"] = "Wave {0} / {1}",
                    ["hud.pill_skip_text"] = "+30c  {0:F1}s  +{1}%",
                    ["hud.streak_text"] = "+{0}%",

                    // ── Radial menu ────────────────────────────────────────────────
                    ["hud.radial_title"] = "{0}  L2  — Choose L3 (irreversible except sell)",
                    ["hud.radial_sell"] = "Sell +{0}g",
                    ["hud.radial_branch_dps"] = "DPS",
                    ["hud.radial_branch_utility"] = "Utility",

                    // DPS branch names per tower
                    ["hud.radial_dps.archer"] = "Sniper",
                    ["hud.radial_dps.mage"] = "Arcane",
                    ["hud.radial_dps.ballista"] = "Pierce Inf.",
                    ["hud.radial_dps.cannon"] = "Mega Shell",

                    // DPS branch hints per tower
                    ["hud.radial_dps_hint.archer"] = "x3 dmg, rate /2",
                    ["hud.radial_dps_hint.mage"] = "x2.5 dmg, slow 30%",
                    ["hud.radial_dps_hint.ballista"] = "x2.5 dmg, pierce 99",
                    ["hud.radial_dps_hint.cannon"] = "x3 dmg, slow 50%",
                    ["hud.radial_dps_hint.default"] = "+Pure DPS",

                    // Utility branch names per tower
                    ["hud.radial_util.archer"] = "Rain",
                    ["hud.radial_util.mage"] = "Fireball",
                    ["hud.radial_util.ballista"] = "Explosion",
                    ["hud.radial_util.cannon"] = "Shotgun",

                    // Utility branch hints per tower
                    ["hud.radial_util_hint.archer"] = "multiShot 2, AOE 3",
                    ["hud.radial_util_hint.mage"] = "AOE 4, burn DOT 3s",
                    ["hud.radial_util_hint.ballista"] = "AOE 5, knockback",
                    ["hud.radial_util_hint.cannon"] = "5 projectiles, AOE 2",
                    ["hud.radial_util_hint.default"] = "+AOE crowd",

                    // ── Tooltip stats ───────────────────────────────────────────────
                    ["tooltip.branch_dps"] = "DPS",
                    ["tooltip.branch_utility"] = "Utility",
                    ["tooltip.invested"] = "{0}g invested",
                    ["tooltip.stat_dmg"] = "Dmg",
                    ["tooltip.stat_dmg_buff"] = " (x{0} buff)",
                    ["tooltip.stat_range"] = "Range",
                    ["tooltip.stat_rate"] = "Rate",
                    ["tooltip.stat_pierce"] = "Pierce",
                    ["tooltip.stat_multishot"] = "MultiShot +{0}",
                    ["tooltip.syn_aura_dmg"] = "Aura dmg x{0}",
                    ["tooltip.syn_pierce"] = "Pierce +{0}",
                    ["tooltip.syn_multishot"] = "MultiShot +{0}",
                    ["tooltip.syn_flyer_dmg"] = "Flyer dmg x{0}",
                    ["tooltip.syn_slow_on_hit"] = "Slow on hit x{0} {1}s",
                    ["tooltip.syn_applies_slow"] = "Applies slow x{0}",
                    ["tooltip.syn_prop_aoe"] = "PropAoE r{0} dmg {1}",
                    ["tooltip.syn_cascade"] = "Cascade r{0}",
                    ["tooltip.syn_knockback"] = "Knockback {0}",
                    ["tooltip.syn_freeze"] = "Freeze {0}s",
                    ["tooltip.syn_propagate_debuff"] = "PropagateDebuff",
                    ["tooltip.syn_pull"] = "Pull active",
                    ["tooltip.pierce_inf"] = "inf",

                    // ── Overlay panels ─────────────────────────────────────────────
                    ["overlay.game_over_title"] = "GAME OVER",
                    ["overlay.game_over_subtitle"] = "The castle has fallen.",
                    ["overlay.victory_title"] = "VICTORY",
                    ["overlay.victory_subtitle"] = "Level cleared.",
                    ["overlay.btn_restart"] = "Restart",
                    ["overlay.btn_retry"] = "Replay",
                    ["overlay.btn_menu"] = "Back to menu",

                    // ── Level select / menu ────────────────────────────────────────
                    ["menu.game_title"] = "CROWD DEFENSE",
                    ["menu.level_select_title"] = "Select a level",
                    ["menu.world_label"] = "W{0}",
                    ["menu.level_btn"] = "{0}-{1}",

                    // ── WorldMap ───────────────────────────────────────────────────
                    ["worldmap.title"] = "CROWD DEFENSE",
                    ["worldmap.total_stars"] = "{0} stars",
                    ["worldmap.locked"] = "Locked",
                    ["worldmap.stars_1"] = "1 star",
                    ["worldmap.stars_2"] = "2 stars",
                    ["worldmap.stars_3"] = "3 stars",
                    ["worldmap.level_showcase"] = "Showcase",
                    ["worldmap.level_boss"] = "Boss",
                    ["worldmap.world1"] = "Plains",
                    ["worldmap.world2"] = "Forest",
                    ["worldmap.world3"] = "Desert",
                    ["worldmap.world4"] = "Volcano",
                    ["worldmap.world5"] = "Fair",
                    ["worldmap.world6"] = "Apocalypse",
                    ["worldmap.world7"] = "Space",
                    ["worldmap.world8"] = "Underwater",
                    ["worldmap.world9"] = "Medieval",
                    ["worldmap.world10"] = "Cyberpunk",

                    // ── Settings panel ─────────────────────────────────────────────
                    ["settings.title"] = "Settings",
                    ["settings.audio_section"] = "Audio",
                    ["settings.master"] = "Master",
                    ["settings.sfx"] = "SFX",
                    ["settings.music"] = "Music",
                    ["settings.mute"] = "Mute",
                    ["settings.gfx_section"] = "Graphics",
                    ["settings.quality"] = "Quality",
                    ["settings.quality_mobile"] = "Mobile",
                    ["settings.quality_desktop"] = "Desktop",
                    ["settings.quality_high"] = "High",
                    ["settings.vfx"] = "VFX",
                    ["settings.shake"] = "Camera shake",
                    ["settings.a11y_section"] = "Accessibility",
                    ["settings.colorblind"] = "Colorblind mode",
                    ["settings.reduce_motion"] = "Reduce motion",
                    ["settings.large_text"] = "Large text",
                    ["settings.lang_section"] = "Language",
                    ["settings.lang_label"] = "Locale",
                    ["settings.close"] = "Close",
                    ["settings.lang_en"] = "English",
                    ["settings.lang_fr"] = "Français",

                    // ── Cutscene ───────────────────────────────────────────────────
                    ["cutscene.continue_hint"] = "[Click / Space]",

                    // ── Skin picker ────────────────────────────────────────────────
                    ["skin.title"] = "Skins",
                    ["skin.category_hero"] = "Hero",
                    ["skin.category_castle"] = "Castle",
                    ["skin.category_vfx"] = "Effects",
                    ["skin.locked"] = "Locked",
                    ["skin.equipped"] = "Equipped",
                    ["skin.equip_btn"] = "Equip",
                    ["skin.close"] = "Close",
                },
                ["fr"] = new()
                {
                    // ── Tower toolbar ──────────────────────────────────────────────
                    ["toolbar.not_enough_gold"] = "Pas assez d'or",

                    // ── Speed control ──────────────────────────────────────────────
                    ["hud.speed_label"] = "VITESSE",

                    // ── Perk picker ────────────────────────────────────────────────
                    ["perk.pick_title"] = "Choisir un bonus",
                    ["perk.pick_subtitle"] = "Choisir 1 parmi 3 pour continuer",
                    ["perk.rarity_common"] = "Commun",
                    ["perk.rarity_rare"] = "Rare",
                    ["perk.rarity_epic"] = "Epique",
                    ["perk.rarity_legendary"] = "Legendaire",
                    ["perk.placeholder_name"] = "Bonus inconnu",
                    ["perk.placeholder_desc"] = "Aucune description disponible.",

                    // ── HUD pills ───────────────────────────────────────────────────
                    ["hud.gold_label"] = "OR",
                    ["hud.wave_label"] = "VAGUE",
                    ["hud.hp_label"] = "PV",
                    ["hud.wave_launch"] = "Lancer la vague [N]",
                    ["hud.wave_launch_bonus"] = "Lancer (+30c) [N]",
                    ["hud.wave_progress"] = "Vague {0} / {1}",
                    ["hud.pill_skip_text"] = "+30c  {0:F1}s  +{1}%",
                    ["hud.streak_text"] = "+{0}%",

                    // ── Radial menu ────────────────────────────────────────────────
                    ["hud.radial_title"] = "{0}  L2  — Choisir L3 (irréversible sauf vente)",
                    ["hud.radial_sell"] = "Vendre +{0}g",
                    ["hud.radial_branch_dps"] = "DPS",
                    ["hud.radial_branch_utility"] = "Utilitaire",

                    // DPS branch names per tower
                    ["hud.radial_dps.archer"] = "Sniper",
                    ["hud.radial_dps.mage"] = "Arcane",
                    ["hud.radial_dps.ballista"] = "Perçage Inf.",
                    ["hud.radial_dps.cannon"] = "Mega Obus",

                    // DPS branch hints per tower
                    ["hud.radial_dps_hint.archer"] = "x3 dmg, cadence /2",
                    ["hud.radial_dps_hint.mage"] = "x2.5 dmg, ralenti 30%",
                    ["hud.radial_dps_hint.ballista"] = "x2.5 dmg, perce 99",
                    ["hud.radial_dps_hint.cannon"] = "x3 dmg, ralenti 50%",
                    ["hud.radial_dps_hint.default"] = "+DPS pur",

                    // Utility branch names per tower
                    ["hud.radial_util.archer"] = "Pluie",
                    ["hud.radial_util.mage"] = "Boule de feu",
                    ["hud.radial_util.ballista"] = "Explosion",
                    ["hud.radial_util.cannon"] = "Shotgun",

                    // Utility branch hints per tower
                    ["hud.radial_util_hint.archer"] = "multiShot 2, AOE 3",
                    ["hud.radial_util_hint.mage"] = "AOE 4, brûlure DOT 3s",
                    ["hud.radial_util_hint.ballista"] = "AOE 5, recul",
                    ["hud.radial_util_hint.cannon"] = "5 projectiles, AOE 2",
                    ["hud.radial_util_hint.default"] = "+AOE foule",

                    // ── Tooltip stats ───────────────────────────────────────────────
                    ["tooltip.branch_dps"] = "DPS",
                    ["tooltip.branch_utility"] = "Utilitaire",
                    ["tooltip.invested"] = "{0}g investi",
                    ["tooltip.stat_dmg"] = "Dmg",
                    ["tooltip.stat_dmg_buff"] = " (x{0} buff)",
                    ["tooltip.stat_range"] = "Portée",
                    ["tooltip.stat_rate"] = "Cadence",
                    ["tooltip.stat_pierce"] = "Perce",
                    ["tooltip.stat_multishot"] = "MultiShot +{0}",
                    ["tooltip.syn_aura_dmg"] = "Aura dmg x{0}",
                    ["tooltip.syn_pierce"] = "Perce +{0}",
                    ["tooltip.syn_multishot"] = "MultiShot +{0}",
                    ["tooltip.syn_flyer_dmg"] = "Dmg volant x{0}",
                    ["tooltip.syn_slow_on_hit"] = "Ralenti au contact x{0} {1}s",
                    ["tooltip.syn_applies_slow"] = "Applique ralenti x{0}",
                    ["tooltip.syn_prop_aoe"] = "PropAOE r{0} dmg {1}",
                    ["tooltip.syn_cascade"] = "Cascade r{0}",
                    ["tooltip.syn_knockback"] = "Recul {0}",
                    ["tooltip.syn_freeze"] = "Gel {0}s",
                    ["tooltip.syn_propagate_debuff"] = "PropaguerDébuff",
                    ["tooltip.syn_pull"] = "Attraction active",
                    ["tooltip.pierce_inf"] = "inf",

                    // ── Overlay panels ─────────────────────────────────────────────
                    ["overlay.game_over_title"] = "GAME OVER",
                    ["overlay.game_over_subtitle"] = "Le château est tombé.",
                    ["overlay.victory_title"] = "VICTOIRE",
                    ["overlay.victory_subtitle"] = "Niveau terminé.",
                    ["overlay.btn_restart"] = "Recommencer",
                    ["overlay.btn_retry"] = "Rejouer",
                    ["overlay.btn_menu"] = "Retour au menu",

                    // ── Level select / menu ────────────────────────────────────────
                    ["menu.game_title"] = "CROWD DEFENSE",
                    ["menu.level_select_title"] = "Choisir un niveau",
                    ["menu.world_label"] = "M{0}",
                    ["menu.level_btn"] = "{0}-{1}",

                    // ── WorldMap ───────────────────────────────────────────────────
                    ["worldmap.title"] = "CROWD DEFENSE",
                    ["worldmap.total_stars"] = "{0} étoiles",
                    ["worldmap.locked"] = "Verrouillé",
                    ["worldmap.stars_1"] = "1 étoile",
                    ["worldmap.stars_2"] = "2 étoiles",
                    ["worldmap.stars_3"] = "3 étoiles",
                    ["worldmap.level_showcase"] = "Showcase",
                    ["worldmap.level_boss"] = "Boss",
                    ["worldmap.world1"] = "Plaine",
                    ["worldmap.world2"] = "Forêt",
                    ["worldmap.world3"] = "Désert",
                    ["worldmap.world4"] = "Volcan",
                    ["worldmap.world5"] = "Foire",
                    ["worldmap.world6"] = "Apocalypse",
                    ["worldmap.world7"] = "Espace",
                    ["worldmap.world8"] = "Sous-marin",
                    ["worldmap.world9"] = "Médiéval",
                    ["worldmap.world10"] = "Cyberpunk",

                    // ── Settings panel ─────────────────────────────────────────────
                    ["settings.title"] = "Paramètres",
                    ["settings.audio_section"] = "Audio",
                    ["settings.master"] = "Général",
                    ["settings.sfx"] = "Effets",
                    ["settings.music"] = "Musique",
                    ["settings.mute"] = "Muet",
                    ["settings.gfx_section"] = "Graphismes",
                    ["settings.quality"] = "Qualité",
                    ["settings.quality_mobile"] = "Mobile",
                    ["settings.quality_desktop"] = "Bureau",
                    ["settings.quality_high"] = "Élevé",
                    ["settings.vfx"] = "VFX",
                    ["settings.shake"] = "Tremblement caméra",
                    ["settings.a11y_section"] = "Accessibilité",
                    ["settings.colorblind"] = "Mode daltonien",
                    ["settings.reduce_motion"] = "Réduire le mouvement",
                    ["settings.large_text"] = "Texte large",
                    ["settings.lang_section"] = "Langue",
                    ["settings.lang_label"] = "Locale",
                    ["settings.close"] = "Fermer",
                    ["settings.lang_en"] = "English",
                    ["settings.lang_fr"] = "Français",

                    // ── Cutscene ───────────────────────────────────────────────────
                    ["cutscene.continue_hint"] = "[Clic / Espace]",

                    // ── Skin picker ────────────────────────────────────────────────
                    ["skin.title"] = "Skins",
                    ["skin.category_hero"] = "Héros",
                    ["skin.category_castle"] = "Château",
                    ["skin.category_vfx"] = "Effets",
                    ["skin.locked"] = "Verrouillé",
                    ["skin.equipped"] = "Équipé",
                    ["skin.equip_btn"] = "Équiper",
                    ["skin.close"] = "Fermer",
                },
            },

            // ── Tower names + descriptions ─────────────────────────────────────────
            ["Towers"] = new()
            {
                ["en"] = new()
                {
                    ["tower.archer.name"] = "Archer",
                    ["tower.archer.desc"] = "Fast single-target attack. Signature: Sniper (DPS) / Rain (Utility).",
                    ["tower.mage.name"] = "Mage",
                    ["tower.mage.desc"] = "Magic damage with slow effect. Signature: Arcane (DPS) / Fireball (Utility).",
                    ["tower.ballista.name"] = "Ballista",
                    ["tower.ballista.desc"] = "High piercing damage. Signature: Pierce Inf. (DPS) / Explosion (Utility).",
                    ["tower.cannon.name"] = "Cannon",
                    ["tower.cannon.desc"] = "AoE blast with slow. Signature: Mega Shell (DPS) / Shotgun (Utility).",
                    ["tower.crossbow.name"] = "Crossbow",
                    ["tower.crossbow.desc"] = "Multi-shot rapid fire support tower.",
                    ["tower.frost.name"] = "Frost",
                    ["tower.frost.desc"] = "Area slow tower. Synergizes to freeze and multi-shot.",
                    ["tower.fan.name"] = "Fan",
                    ["tower.fan.desc"] = "Wide cone attack, knockback support.",
                    ["tower.acid.name"] = "Acid",
                    ["tower.acid.desc"] = "Armor break on hit. Increases damage taken by enemies.",
                    ["tower.mine.name"] = "Mine",
                    ["tower.mine.desc"] = "Timed AoE explosive. Cascade synergy with Cannon.",
                    ["tower.portal.name"] = "Portal",
                    ["tower.portal.desc"] = "Aura that buffs nearby attack towers.",
                    ["tower.magnet.name"] = "Magnet",
                    ["tower.magnet.desc"] = "Pulls coins, increases coin drops from enemies.",
                    ["tower.skyguard.name"] = "Skyguard",
                    ["tower.skyguard.desc"] = "Anti-air specialist. Targets flyers only.",
                    ["tower.tank.name"] = "Tank",
                    ["tower.tank.desc"] = "Heavy slow tower. Pull synergy with Magnet.",
                },
                ["fr"] = new()
                {
                    ["tower.archer.name"] = "Archer",
                    ["tower.archer.desc"] = "Attaque rapide cible unique. Signature : Sniper (DPS) / Pluie (Utilitaire).",
                    ["tower.mage.name"] = "Mage",
                    ["tower.mage.desc"] = "Dégâts magiques avec ralentissement. Signature : Arcane (DPS) / Boule de feu (Utilitaire).",
                    ["tower.ballista.name"] = "Baliste",
                    ["tower.ballista.desc"] = "Dégâts de perçage élevés. Signature : Perçage Inf. (DPS) / Explosion (Utilitaire).",
                    ["tower.cannon.name"] = "Canon",
                    ["tower.cannon.desc"] = "Explosion AOE avec ralentissement. Signature : Mega Obus (DPS) / Shotgun (Utilitaire).",
                    ["tower.crossbow.name"] = "Arbalète",
                    ["tower.crossbow.desc"] = "Tour de soutien à tir rapide multi-projectiles.",
                    ["tower.frost.name"] = "Glace",
                    ["tower.frost.desc"] = "Tour de ralentissement de zone. Synergie gel et multi-tir.",
                    ["tower.fan.name"] = "Ventilateur",
                    ["tower.fan.desc"] = "Attaque en cône large, soutien recul.",
                    ["tower.acid.name"] = "Acide",
                    ["tower.acid.desc"] = "Brise l'armure au contact. Augmente les dégâts subis.",
                    ["tower.mine.name"] = "Mine",
                    ["tower.mine.desc"] = "Explosif AOE à retardement. Synergie cascade avec Canon.",
                    ["tower.portal.name"] = "Portail",
                    ["tower.portal.desc"] = "Aura qui améliore les tours d'attaque proches.",
                    ["tower.magnet.name"] = "Aimant",
                    ["tower.magnet.desc"] = "Attire les pièces, augmente les récompenses ennemies.",
                    ["tower.skyguard.name"] = "Garde-ciel",
                    ["tower.skyguard.desc"] = "Spécialiste anti-aérien. Cible les volants uniquement.",
                    ["tower.tank.name"] = "Tank",
                    ["tower.tank.desc"] = "Tour lourde de ralentissement. Synergie attraction avec Aimant.",
                },
            },

            // ── Enemy names ────────────────────────────────────────────────────────
            ["Enemies"] = new()
            {
                ["en"] = new()
                {
                    ["enemy.basic.name"] = "Basic",
                    ["enemy.runner.name"] = "Runner",
                    ["enemy.brute.name"] = "Brute",
                    ["enemy.flyer.name"] = "Flyer",
                    ["enemy.shielded.name"] = "Shielded",
                    ["enemy.assassin.name"] = "Assassin",
                    ["enemy.imp.name"] = "Imp",
                    ["enemy.boss.name"] = "Boss",
                    ["enemy.midboss.name"] = "Mid-Boss",
                    ["enemy.plaine_pigeon.name"] = "Pigeon",
                    ["enemy.forest_bee.name"] = "Forest Bee",
                    ["enemy.forest_brute.name"] = "Forest Brute",
                    ["enemy.desert_runner.name"] = "Desert Runner",
                    ["enemy.submarim_runner.name"] = "Subterranean Runner",
                    ["enemy.cyber_basic.name"] = "Cyber Basic",
                    ["enemy.cyber_runner.name"] = "Cyber Runner",
                    ["enemy.cyber_brute.name"] = "Cyber Brute",
                    ["enemy.cyber_flyer.name"] = "Cyber Flyer",
                    ["enemy.skeleton_minion.name"] = "Skeleton Minion",
                    ["enemy.ai_hub.name"] = "AI Hub",
                    ["enemy.brigand_boss.name"] = "Brigand Boss",
                    ["enemy.corsair_boss.name"] = "Corsair Boss",
                    ["enemy.warlord_boss.name"] = "Warlord Boss",
                    ["enemy.dragon_boss.name"] = "Dragon Boss",
                    ["enemy.kraken_boss.name"] = "Kraken Boss",
                    ["enemy.wizard_king.name"] = "Wizard King",
                    ["enemy.cosmic_boss.name"] = "Cosmic Boss",
                    ["enemy.apocalypse_boss.name"] = "Apocalypse Boss",
                },
                ["fr"] = new()
                {
                    ["enemy.basic.name"] = "Basique",
                    ["enemy.runner.name"] = "Coureur",
                    ["enemy.brute.name"] = "Brute",
                    ["enemy.flyer.name"] = "Volant",
                    ["enemy.shielded.name"] = "Bouclier",
                    ["enemy.assassin.name"] = "Assassin",
                    ["enemy.imp.name"] = "Diablotin",
                    ["enemy.boss.name"] = "Boss",
                    ["enemy.midboss.name"] = "Mini-Boss",
                    ["enemy.plaine_pigeon.name"] = "Pigeon",
                    ["enemy.forest_bee.name"] = "Abeille Forêt",
                    ["enemy.forest_brute.name"] = "Brute Forêt",
                    ["enemy.desert_runner.name"] = "Coureur Désert",
                    ["enemy.submarim_runner.name"] = "Coureur Souterrain",
                    ["enemy.cyber_basic.name"] = "Cyber Basique",
                    ["enemy.cyber_runner.name"] = "Cyber Coureur",
                    ["enemy.cyber_brute.name"] = "Cyber Brute",
                    ["enemy.cyber_flyer.name"] = "Cyber Volant",
                    ["enemy.skeleton_minion.name"] = "Squelette Serviteur",
                    ["enemy.ai_hub.name"] = "Hub IA",
                    ["enemy.brigand_boss.name"] = "Boss Brigand",
                    ["enemy.corsair_boss.name"] = "Boss Corsaire",
                    ["enemy.warlord_boss.name"] = "Boss Seigneur de Guerre",
                    ["enemy.dragon_boss.name"] = "Boss Dragon",
                    ["enemy.kraken_boss.name"] = "Boss Kraken",
                    ["enemy.wizard_king.name"] = "Roi Sorcier",
                    ["enemy.cosmic_boss.name"] = "Boss Cosmique",
                    ["enemy.apocalypse_boss.name"] = "Boss Apocalypse",
                },
            },

            // ── Level names + briefings ────────────────────────────────────────────
            ["Levels"] = new()
            {
                ["en"] = new()
                {
                    ["level.world1_1.name"] = "W1-1: Plains Gate",
                    ["level.world1_2.name"] = "W1-2: Valley Path",
                    ["level.world1_3.name"] = "W1-3: River Crossing",
                    ["level.world1_4.name"] = "W1-4: Forest Edge",
                    ["level.world1_5.name"] = "W1-5: Hilltop",
                    ["level.world1_6.name"] = "W1-6: The Gorge",
                    ["level.world1_7.name"] = "W1-7: Outpost",
                    ["level.world1_8.name"] = "W1-8: Brigand Pass",
                    ["level.world2_1.name"] = "W2-1: Forest Entrance",
                    ["level.world2_2.name"] = "W2-2: Deep Woods",
                    ["level.world2_3.name"] = "W2-3: Bee Hollow",
                    ["level.world2_4.name"] = "W2-4: Mossy Bridge",
                    ["level.world2_5.name"] = "W2-5: Ancient Ruins",
                    ["level.world2_6.name"] = "W2-6: Canopy Trail",
                    ["level.world2_7.name"] = "W2-7: Root Maze",
                    ["level.world2_8.name"] = "W2-8: Corsair Ambush",
                    ["level.world3_1.name"] = "W3-1: Desert Dunes",
                    ["level.world3_2.name"] = "W3-2: Sand Storm",
                    ["level.world3_3.name"] = "W3-3: Oasis",
                    ["level.world3_4.name"] = "W3-4: Rocky Plateau",
                    ["level.world3_5.name"] = "W3-5: Scorched Earth",
                    ["level.world3_6.name"] = "W3-6: Cactus Field",
                    ["level.world3_7.name"] = "W3-7: Mirage",
                    ["level.world3_8.name"] = "W3-8: Warlord Front",
                    ["level.world4_1.name"] = "W4-1: Tundra",
                    ["level.world4_2.name"] = "W4-2: Frozen Lake",
                    ["level.world4_3.name"] = "W4-3: Ice Cavern",
                    ["level.world4_4.name"] = "W4-4: Glacier Pass",
                    ["level.world4_5.name"] = "W4-5: Blizzard Peak",
                    ["level.world4_6.name"] = "W4-6: Permafrost",
                    ["level.world4_7.name"] = "W4-7: Aurora Ridge",
                    ["level.world4_8.name"] = "W4-8: Dragon Lair",
                    ["level.world5_1.name"] = "W5-1: Harbor",
                    ["level.world5_2.name"] = "W5-2: Sea Cliffs",
                    ["level.world5_3.name"] = "W5-3: Coral Reef",
                    ["level.world5_4.name"] = "W5-4: Shipwreck Bay",
                    ["level.world5_5.name"] = "W5-5: Tidal Caves",
                    ["level.world5_6.name"] = "W5-6: Storm Surge",
                    ["level.world5_7.name"] = "W5-7: Deep Current",
                    ["level.world5_8.name"] = "W5-8: Kraken Depths",
                    ["level.world6_1.name"] = "W6-1: Catacombs",
                    ["level.world6_2.name"] = "W6-2: Bone Hall",
                    ["level.world6_3.name"] = "W6-3: Cursed Altar",
                    ["level.world6_4.name"] = "W6-4: Dark Spire",
                    ["level.world6_5.name"] = "W6-5: Necropolis Gate",
                    ["level.world6_6.name"] = "W6-6: Shadow Veil",
                    ["level.world6_7.name"] = "W6-7: Lich Tower",
                    ["level.world6_8.name"] = "W6-8: Wizard King's Keep",
                    ["level.world7_1.name"] = "W7-1: Cyber Outskirts",
                    ["level.world7_2.name"] = "W7-2: Data Stream",
                    ["level.world7_3.name"] = "W7-3: Server Farm",
                    ["level.world7_4.name"] = "W7-4: Neural Grid",
                    ["level.world7_5.name"] = "W7-5: Protocol Wall",
                    ["level.world7_6.name"] = "W7-6: Binary Maze",
                    ["level.world7_7.name"] = "W7-7: Core Access",
                    ["level.world7_8.name"] = "W7-8: AI Hub Siege",
                    ["level.world8_1.name"] = "W8-1: Volcanic Foothills",
                    ["level.world8_2.name"] = "W8-2: Lava Fields",
                    ["level.world8_3.name"] = "W8-3: Magma Chamber",
                    ["level.world8_4.name"] = "W8-4: Obsidian Bridge",
                    ["level.world8_5.name"] = "W8-5: Caldron Pass",
                    ["level.world8_6.name"] = "W8-6: Fire Rift",
                    ["level.world8_7.name"] = "W8-7: Inferno Summit",
                    ["level.world8_8.name"] = "W8-8: Infernal Boss",
                    ["level.world9_1.name"] = "W9-1: Skyreach",
                    ["level.world9_2.name"] = "W9-2: Cloud Platform",
                    ["level.world9_3.name"] = "W9-3: Wind Shear",
                    ["level.world9_4.name"] = "W9-4: Storm Eye",
                    ["level.world9_5.name"] = "W9-5: Lightning Spire",
                    ["level.world9_6.name"] = "W9-6: Celestial Gate",
                    ["level.world9_7.name"] = "W9-7: Void Rift",
                    ["level.world9_8.name"] = "W9-8: Cosmic Guardian",
                    ["level.world10_1.name"] = "W10-1: Apocalypse Dawn",
                    ["level.world10_2.name"] = "W10-2: Reckoning",
                    ["level.world10_3.name"] = "W10-3: The Horde",
                    ["level.world10_4.name"] = "W10-4: Siege of Ages",
                    ["level.world10_5.name"] = "W10-5: Last Wall",
                    ["level.world10_6.name"] = "W10-6: Final Push",
                    ["level.world10_7.name"] = "W10-7: Endgame",
                    ["level.world10_8.name"] = "W10-8: Apocalypse Boss",

                    // Briefings — TBD, using placeholder text
                    ["level.world1_1.briefing"] = "[Briefing TBD]",
                    ["level.world1_2.briefing"] = "[Briefing TBD]",
                    ["level.world1_3.briefing"] = "[Briefing TBD]",
                    ["level.world1_4.briefing"] = "[Briefing TBD]",
                    ["level.world1_5.briefing"] = "[Briefing TBD]",
                    ["level.world1_6.briefing"] = "[Briefing TBD]",
                    ["level.world1_7.briefing"] = "[Briefing TBD]",
                    ["level.world1_8.briefing"] = "[Briefing TBD]",
                    ["level.world2_1.briefing"] = "[Briefing TBD]",
                    ["level.world2_2.briefing"] = "[Briefing TBD]",
                    ["level.world2_3.briefing"] = "[Briefing TBD]",
                    ["level.world2_4.briefing"] = "[Briefing TBD]",
                    ["level.world2_5.briefing"] = "[Briefing TBD]",
                    ["level.world2_6.briefing"] = "[Briefing TBD]",
                    ["level.world2_7.briefing"] = "[Briefing TBD]",
                    ["level.world2_8.briefing"] = "[Briefing TBD]",
                    ["level.world3_1.briefing"] = "[Briefing TBD]",
                    ["level.world3_2.briefing"] = "[Briefing TBD]",
                    ["level.world3_3.briefing"] = "[Briefing TBD]",
                    ["level.world3_4.briefing"] = "[Briefing TBD]",
                    ["level.world3_5.briefing"] = "[Briefing TBD]",
                    ["level.world3_6.briefing"] = "[Briefing TBD]",
                    ["level.world3_7.briefing"] = "[Briefing TBD]",
                    ["level.world3_8.briefing"] = "[Briefing TBD]",
                    ["level.world4_1.briefing"] = "[Briefing TBD]",
                    ["level.world4_2.briefing"] = "[Briefing TBD]",
                    ["level.world4_3.briefing"] = "[Briefing TBD]",
                    ["level.world4_4.briefing"] = "[Briefing TBD]",
                    ["level.world4_5.briefing"] = "[Briefing TBD]",
                    ["level.world4_6.briefing"] = "[Briefing TBD]",
                    ["level.world4_7.briefing"] = "[Briefing TBD]",
                    ["level.world4_8.briefing"] = "[Briefing TBD]",
                    ["level.world5_1.briefing"] = "[Briefing TBD]",
                    ["level.world5_2.briefing"] = "[Briefing TBD]",
                    ["level.world5_3.briefing"] = "[Briefing TBD]",
                    ["level.world5_4.briefing"] = "[Briefing TBD]",
                    ["level.world5_5.briefing"] = "[Briefing TBD]",
                    ["level.world5_6.briefing"] = "[Briefing TBD]",
                    ["level.world5_7.briefing"] = "[Briefing TBD]",
                    ["level.world5_8.briefing"] = "[Briefing TBD]",
                    ["level.world6_1.briefing"] = "[Briefing TBD]",
                    ["level.world6_2.briefing"] = "[Briefing TBD]",
                    ["level.world6_3.briefing"] = "[Briefing TBD]",
                    ["level.world6_4.briefing"] = "[Briefing TBD]",
                    ["level.world6_5.briefing"] = "[Briefing TBD]",
                    ["level.world6_6.briefing"] = "[Briefing TBD]",
                    ["level.world6_7.briefing"] = "[Briefing TBD]",
                    ["level.world6_8.briefing"] = "[Briefing TBD]",
                    ["level.world7_1.briefing"] = "[Briefing TBD]",
                    ["level.world7_2.briefing"] = "[Briefing TBD]",
                    ["level.world7_3.briefing"] = "[Briefing TBD]",
                    ["level.world7_4.briefing"] = "[Briefing TBD]",
                    ["level.world7_5.briefing"] = "[Briefing TBD]",
                    ["level.world7_6.briefing"] = "[Briefing TBD]",
                    ["level.world7_7.briefing"] = "[Briefing TBD]",
                    ["level.world7_8.briefing"] = "[Briefing TBD]",
                    ["level.world8_1.briefing"] = "[Briefing TBD]",
                    ["level.world8_2.briefing"] = "[Briefing TBD]",
                    ["level.world8_3.briefing"] = "[Briefing TBD]",
                    ["level.world8_4.briefing"] = "[Briefing TBD]",
                    ["level.world8_5.briefing"] = "[Briefing TBD]",
                    ["level.world8_6.briefing"] = "[Briefing TBD]",
                    ["level.world8_7.briefing"] = "[Briefing TBD]",
                    ["level.world8_8.briefing"] = "[Briefing TBD]",
                    ["level.world9_1.briefing"] = "[Briefing TBD]",
                    ["level.world9_2.briefing"] = "[Briefing TBD]",
                    ["level.world9_3.briefing"] = "[Briefing TBD]",
                    ["level.world9_4.briefing"] = "[Briefing TBD]",
                    ["level.world9_5.briefing"] = "[Briefing TBD]",
                    ["level.world9_6.briefing"] = "[Briefing TBD]",
                    ["level.world9_7.briefing"] = "[Briefing TBD]",
                    ["level.world9_8.briefing"] = "[Briefing TBD]",
                    ["level.world10_1.briefing"] = "[Briefing TBD]",
                    ["level.world10_2.briefing"] = "[Briefing TBD]",
                    ["level.world10_3.briefing"] = "[Briefing TBD]",
                    ["level.world10_4.briefing"] = "[Briefing TBD]",
                    ["level.world10_5.briefing"] = "[Briefing TBD]",
                    ["level.world10_6.briefing"] = "[Briefing TBD]",
                    ["level.world10_7.briefing"] = "[Briefing TBD]",
                    ["level.world10_8.briefing"] = "[Briefing TBD]",
                },
                ["fr"] = new()
                {
                    ["level.world1_1.name"] = "M1-1 : Porte des Plaines",
                    ["level.world1_2.name"] = "M1-2 : Chemin de la Vallée",
                    ["level.world1_3.name"] = "M1-3 : Traversée de Rivière",
                    ["level.world1_4.name"] = "M1-4 : Lisière de Forêt",
                    ["level.world1_5.name"] = "M1-5 : Colline",
                    ["level.world1_6.name"] = "M1-6 : Les Gorges",
                    ["level.world1_7.name"] = "M1-7 : Avant-poste",
                    ["level.world1_8.name"] = "M1-8 : Col du Brigand",
                    ["level.world2_1.name"] = "M2-1 : Entrée de Forêt",
                    ["level.world2_2.name"] = "M2-2 : Forêt Profonde",
                    ["level.world2_3.name"] = "M2-3 : Creux aux Abeilles",
                    ["level.world2_4.name"] = "M2-4 : Pont Moussu",
                    ["level.world2_5.name"] = "M2-5 : Ruines Anciennes",
                    ["level.world2_6.name"] = "M2-6 : Piste de la Canopée",
                    ["level.world2_7.name"] = "M2-7 : Labyrinthe des Racines",
                    ["level.world2_8.name"] = "M2-8 : Embuscade Corsaire",
                    ["level.world3_1.name"] = "M3-1 : Dunes du Désert",
                    ["level.world3_2.name"] = "M3-2 : Tempête de Sable",
                    ["level.world3_3.name"] = "M3-3 : Oasis",
                    ["level.world3_4.name"] = "M3-4 : Plateau Rocheux",
                    ["level.world3_5.name"] = "M3-5 : Terre Brûlée",
                    ["level.world3_6.name"] = "M3-6 : Champ de Cactus",
                    ["level.world3_7.name"] = "M3-7 : Mirage",
                    ["level.world3_8.name"] = "M3-8 : Front du Seigneur",
                    ["level.world4_1.name"] = "M4-1 : Toundra",
                    ["level.world4_2.name"] = "M4-2 : Lac Gelé",
                    ["level.world4_3.name"] = "M4-3 : Caverne de Glace",
                    ["level.world4_4.name"] = "M4-4 : Col du Glacier",
                    ["level.world4_5.name"] = "M4-5 : Pic de Blizzard",
                    ["level.world4_6.name"] = "M4-6 : Permafrost",
                    ["level.world4_7.name"] = "M4-7 : Crête de l'Aurore",
                    ["level.world4_8.name"] = "M4-8 : Antre du Dragon",
                    ["level.world5_1.name"] = "M5-1 : Port",
                    ["level.world5_2.name"] = "M5-2 : Falaises Marines",
                    ["level.world5_3.name"] = "M5-3 : Récif Corallien",
                    ["level.world5_4.name"] = "M5-4 : Baie du Naufrage",
                    ["level.world5_5.name"] = "M5-5 : Grottes des Marées",
                    ["level.world5_6.name"] = "M5-6 : Vague de Tempête",
                    ["level.world5_7.name"] = "M5-7 : Courant Profond",
                    ["level.world5_8.name"] = "M5-8 : Profondeurs du Kraken",
                    ["level.world6_1.name"] = "M6-1 : Catacombes",
                    ["level.world6_2.name"] = "M6-2 : Salle des Os",
                    ["level.world6_3.name"] = "M6-3 : Autel Maudit",
                    ["level.world6_4.name"] = "M6-4 : Tour Sombre",
                    ["level.world6_5.name"] = "M6-5 : Porte de la Nécropole",
                    ["level.world6_6.name"] = "M6-6 : Voile d'Ombre",
                    ["level.world6_7.name"] = "M6-7 : Tour du Liche",
                    ["level.world6_8.name"] = "M6-8 : Donjon du Roi Sorcier",
                    ["level.world7_1.name"] = "M7-1 : Périphérie Cyber",
                    ["level.world7_2.name"] = "M7-2 : Flux de Données",
                    ["level.world7_3.name"] = "M7-3 : Ferme de Serveurs",
                    ["level.world7_4.name"] = "M7-4 : Grille Neurale",
                    ["level.world7_5.name"] = "M7-5 : Mur de Protocole",
                    ["level.world7_6.name"] = "M7-6 : Labyrinthe Binaire",
                    ["level.world7_7.name"] = "M7-7 : Accès au Noyau",
                    ["level.world7_8.name"] = "M7-8 : Siège du Hub IA",
                    ["level.world8_1.name"] = "M8-1 : Contreforts Volcaniques",
                    ["level.world8_2.name"] = "M8-2 : Champs de Lave",
                    ["level.world8_3.name"] = "M8-3 : Chambre Magmatique",
                    ["level.world8_4.name"] = "M8-4 : Pont d'Obsidienne",
                    ["level.world8_5.name"] = "M8-5 : Col du Chaudron",
                    ["level.world8_6.name"] = "M8-6 : Fissure de Feu",
                    ["level.world8_7.name"] = "M8-7 : Sommet de l'Enfer",
                    ["level.world8_8.name"] = "M8-8 : Boss Infernal",
                    ["level.world9_1.name"] = "M9-1 : Cimes Célestes",
                    ["level.world9_2.name"] = "M9-2 : Plateforme Nuageuse",
                    ["level.world9_3.name"] = "M9-3 : Cisaillement de Vent",
                    ["level.world9_4.name"] = "M9-4 : Œil de Tempête",
                    ["level.world9_5.name"] = "M9-5 : Flèche Éclairs",
                    ["level.world9_6.name"] = "M9-6 : Porte Céleste",
                    ["level.world9_7.name"] = "M9-7 : Fissure du Vide",
                    ["level.world9_8.name"] = "M9-8 : Gardien Cosmique",
                    ["level.world10_1.name"] = "M10-1 : Aube de l'Apocalypse",
                    ["level.world10_2.name"] = "M10-2 : Le Jugement",
                    ["level.world10_3.name"] = "M10-3 : La Horde",
                    ["level.world10_4.name"] = "M10-4 : Siège des Âges",
                    ["level.world10_5.name"] = "M10-5 : Dernier Rempart",
                    ["level.world10_6.name"] = "M10-6 : Assaut Final",
                    ["level.world10_7.name"] = "M10-7 : Fin du Jeu",
                    ["level.world10_8.name"] = "M10-8 : Boss Apocalypse",

                    // Briefings FR — TBD
                    ["level.world1_1.briefing"] = "[Briefing à venir]",
                    ["level.world1_2.briefing"] = "[Briefing à venir]",
                    ["level.world1_3.briefing"] = "[Briefing à venir]",
                    ["level.world1_4.briefing"] = "[Briefing à venir]",
                    ["level.world1_5.briefing"] = "[Briefing à venir]",
                    ["level.world1_6.briefing"] = "[Briefing à venir]",
                    ["level.world1_7.briefing"] = "[Briefing à venir]",
                    ["level.world1_8.briefing"] = "[Briefing à venir]",
                    ["level.world2_1.briefing"] = "[Briefing à venir]",
                    ["level.world2_2.briefing"] = "[Briefing à venir]",
                    ["level.world2_3.briefing"] = "[Briefing à venir]",
                    ["level.world2_4.briefing"] = "[Briefing à venir]",
                    ["level.world2_5.briefing"] = "[Briefing à venir]",
                    ["level.world2_6.briefing"] = "[Briefing à venir]",
                    ["level.world2_7.briefing"] = "[Briefing à venir]",
                    ["level.world2_8.briefing"] = "[Briefing à venir]",
                    ["level.world3_1.briefing"] = "[Briefing à venir]",
                    ["level.world3_2.briefing"] = "[Briefing à venir]",
                    ["level.world3_3.briefing"] = "[Briefing à venir]",
                    ["level.world3_4.briefing"] = "[Briefing à venir]",
                    ["level.world3_5.briefing"] = "[Briefing à venir]",
                    ["level.world3_6.briefing"] = "[Briefing à venir]",
                    ["level.world3_7.briefing"] = "[Briefing à venir]",
                    ["level.world3_8.briefing"] = "[Briefing à venir]",
                    ["level.world4_1.briefing"] = "[Briefing à venir]",
                    ["level.world4_2.briefing"] = "[Briefing à venir]",
                    ["level.world4_3.briefing"] = "[Briefing à venir]",
                    ["level.world4_4.briefing"] = "[Briefing à venir]",
                    ["level.world4_5.briefing"] = "[Briefing à venir]",
                    ["level.world4_6.briefing"] = "[Briefing à venir]",
                    ["level.world4_7.briefing"] = "[Briefing à venir]",
                    ["level.world4_8.briefing"] = "[Briefing à venir]",
                    ["level.world5_1.briefing"] = "[Briefing à venir]",
                    ["level.world5_2.briefing"] = "[Briefing à venir]",
                    ["level.world5_3.briefing"] = "[Briefing à venir]",
                    ["level.world5_4.briefing"] = "[Briefing à venir]",
                    ["level.world5_5.briefing"] = "[Briefing à venir]",
                    ["level.world5_6.briefing"] = "[Briefing à venir]",
                    ["level.world5_7.briefing"] = "[Briefing à venir]",
                    ["level.world5_8.briefing"] = "[Briefing à venir]",
                    ["level.world6_1.briefing"] = "[Briefing à venir]",
                    ["level.world6_2.briefing"] = "[Briefing à venir]",
                    ["level.world6_3.briefing"] = "[Briefing à venir]",
                    ["level.world6_4.briefing"] = "[Briefing à venir]",
                    ["level.world6_5.briefing"] = "[Briefing à venir]",
                    ["level.world6_6.briefing"] = "[Briefing à venir]",
                    ["level.world6_7.briefing"] = "[Briefing à venir]",
                    ["level.world6_8.briefing"] = "[Briefing à venir]",
                    ["level.world7_1.briefing"] = "[Briefing à venir]",
                    ["level.world7_2.briefing"] = "[Briefing à venir]",
                    ["level.world7_3.briefing"] = "[Briefing à venir]",
                    ["level.world7_4.briefing"] = "[Briefing à venir]",
                    ["level.world7_5.briefing"] = "[Briefing à venir]",
                    ["level.world7_6.briefing"] = "[Briefing à venir]",
                    ["level.world7_7.briefing"] = "[Briefing à venir]",
                    ["level.world7_8.briefing"] = "[Briefing à venir]",
                    ["level.world8_1.briefing"] = "[Briefing à venir]",
                    ["level.world8_2.briefing"] = "[Briefing à venir]",
                    ["level.world8_3.briefing"] = "[Briefing à venir]",
                    ["level.world8_4.briefing"] = "[Briefing à venir]",
                    ["level.world8_5.briefing"] = "[Briefing à venir]",
                    ["level.world8_6.briefing"] = "[Briefing à venir]",
                    ["level.world8_7.briefing"] = "[Briefing à venir]",
                    ["level.world8_8.briefing"] = "[Briefing à venir]",
                    ["level.world9_1.briefing"] = "[Briefing à venir]",
                    ["level.world9_2.briefing"] = "[Briefing à venir]",
                    ["level.world9_3.briefing"] = "[Briefing à venir]",
                    ["level.world9_4.briefing"] = "[Briefing à venir]",
                    ["level.world9_5.briefing"] = "[Briefing à venir]",
                    ["level.world9_6.briefing"] = "[Briefing à venir]",
                    ["level.world9_7.briefing"] = "[Briefing à venir]",
                    ["level.world9_8.briefing"] = "[Briefing à venir]",
                    ["level.world10_1.briefing"] = "[Briefing à venir]",
                    ["level.world10_2.briefing"] = "[Briefing à venir]",
                    ["level.world10_3.briefing"] = "[Briefing à venir]",
                    ["level.world10_4.briefing"] = "[Briefing à venir]",
                    ["level.world10_5.briefing"] = "[Briefing à venir]",
                    ["level.world10_6.briefing"] = "[Briefing à venir]",
                    ["level.world10_7.briefing"] = "[Briefing à venir]",
                    ["level.world10_8.briefing"] = "[Briefing à venir]",
                },
            },
        };

        public static string Get(string key, string table = "UI")
        {
            if (_fallback.TryGetValue(table, out var tableDict) &&
                tableDict.TryGetValue(_locale, out var localeDict) &&
                localeDict.TryGetValue(key, out var value))
                return value;

            if (_fallback.TryGetValue(table, out var t2) &&
                t2.TryGetValue("en", out var enDict) &&
                enDict.TryGetValue(key, out var en))
                return en;

            return key;
        }

        public static string Get(string key, params object[] args)
        {
            string raw = Get(key);
            if (args == null || args.Length == 0) return raw;
            try { return string.Format(raw, args); }
            catch { return raw; }
        }

        public static void SetLocale(string code)
        {
            if (string.IsNullOrEmpty(code) || _locale == code) return;
            _locale = code;
            OnLocaleChanged?.Invoke();
        }
    }
}
